### PR TITLE
logo for wifiwand

### PR DESCRIPTION
**Pull request by anharismail**

### CODE REVIEW

**Comment by keithrbennett** [comment]
I'd like to use a relative filespec in the repo instead of the absolute link to githubusercontent.com. Would there be any problem with that? I'm thinking something like:

`logo`

A few other things, but I can do these myself:

1) I prefer to avoid spaces in filenames, so I would replace spaces with hyphens and convert all upper case letters to lower case (as in the above example). This makes it much easier to deal with on the command line.

2) I would give the files more descriptive names. One improvement would be to label the "Original 1" files "horizontal" and "Original 2" "vertical", to indicate the logotype/logomark positional relationship. Also, I'd want 'wifiwand' and 'logo' in the filenames, so that if the file were taken outside of the context of the directory in which it lives, there would be more descriptive information. Thus, `wifiwand-logo-horizontal-color.png`. I'm not saying this is right and your approach is wrong, I realize there are reasonable arguments for both sides.

3) What was the logo.md file for? I'm thinking it would be good for displaying all the files so one could see them all at one time.

**Comment by anharismail** [comment]
"I saw the rendering of the readme and I like it a lot, but can you explain to me what you did here? That is, how did you get your content on to githubusercontent.com? Shouldn't we use a URL in the wifi-wand project itself? And is the "readme" arbitrary and invisible because the linked file is an image?"

I usually did it to use my logo in readme, using third party "image source". But, if you think its not appropriate, you can just fix it with the correct way. I did just based on my experience before :)

**Comment by anharismail** [comment]
Sorry for many unappropriate things on my pull request. I'll change the name as you suggested.

and how about if I put it on google drive link, so it can help you decide which better for the repository.

*logo.md is just file to help me create new folder, because it's too hard to make a folder by using web browser.

**Comment by keithrbennett** [comment]
I think we may have had a miscommunication, but thank you very much for the logo. I will merge the pull request and make the changes I mentioned.

**Comment by anharismail** [comment]
@keithrbennett Thanks a lot for your kindness and sorry for many incorrect things. A honour for me that my logo used on this repository.

**Comment by keithrbennett** [comment]
@anharismail No problem at all, thank you too! I like the icon.

Would it be ok for us to correspond privately? There are a couple of things
I'd like to speak with you about. If so, I have followed you on Twitter,
and if you follow me back we can send direct messages to each other.

**Comment by anharismail** [comment]
Yes, please. I'll follow you back @keithrbennett

**Pull request merged**
